<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="BUCK_VC_FIX_FQ" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0" description="APP can be used to control different configurations of a buck converter in voltage mode using fixed frequency." mode="NOTSHARABLE" version="4.1.4" minDaveVersion="4.0.0" instanceLabel="BUCK_VC_FIX_FQ_0" appLabel="" containingProxySignal="true">
  <properties provideInit="true"/>
  <virtualSignals name="vout_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_io" hwSignal="pad" hwResource="//@hwResources.0"/>
  <virtualSignals name="vin_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_io" hwSignal="pad" hwResource="//@hwResources.1" required="false"/>
  <virtualSignals name="iout1_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_io" hwSignal="pad" hwResource="//@hwResources.2" required="false"/>
  <virtualSignals name="iout2_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_io" hwSignal="pad" hwResource="//@hwResources.3" required="false"/>
  <virtualSignals name="iout3_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_io" hwSignal="pad" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="iout4_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_io" hwSignal="pad" hwResource="//@hwResources.5" required="false"/>
  <virtualSignals name="User_Defined_pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_io" hwSignal="pad" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="vout_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1" hwSignal="gch" hwResource="//@hwResources.7"/>
  <virtualSignals name="vin_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2" hwSignal="gch" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="iout1_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3" hwSignal="gch" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="iout2_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4" hwSignal="gch" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="iout3_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5" hwSignal="gch" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="iout4_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6" hwSignal="gch" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="user_defined_channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7" hwSignal="gch" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="vout_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.7"/>
  <virtualSignals name="vin_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="iout1_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="iout2_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="iout3_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="iout4_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="user_defined_channel_iclass" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_iclass_sel" hwSignal="iclass_sel" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="vout_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_sel" hwSignal="select" hwResource="//@hwResources.7"/>
  <virtualSignals name="vin_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_sel" hwSignal="select" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="iout1_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_sel" hwSignal="select" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="iout2_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_sel" hwSignal="select" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="iout3_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_sel" hwSignal="select" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="iout4_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_sel" hwSignal="select" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="user_defined_channel_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_sel" hwSignal="select" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="vout_result_event" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_result_event_out" hwSignal="rev" hwResource="//@hwResources.14"/>
  <virtualSignals name="nvic_node" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_nvic_signal_in" hwSignal="signal_in" hwResource="//@hwResources.21"/>
  <virtualSignals name="vout_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_ressel" hwSignal="res_sel" hwResource="//@hwResources.7"/>
  <virtualSignals name="vin_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_ressel" hwSignal="res_sel" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="iout1_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_ressel" hwSignal="res_sel" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="iout2_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_ressel" hwSignal="res_sel" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="iout3_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_ressel" hwSignal="res_sel" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="iout4_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_ressel" hwSignal="res_sel" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="user_defined_result_select" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_ressel" hwSignal="res_sel" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="vout_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_res" hwSignal="res_sel" hwResource="//@hwResources.14"/>
  <virtualSignals name="vin_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_res" hwSignal="res_sel" hwResource="//@hwResources.15" required="false"/>
  <virtualSignals name="iout1_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_res" hwSignal="res_sel" hwResource="//@hwResources.16" required="false"/>
  <virtualSignals name="iout2_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_res" hwSignal="res_sel" hwResource="//@hwResources.17" required="false"/>
  <virtualSignals name="iout3_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_res" hwSignal="res_sel" hwResource="//@hwResources.18" required="false"/>
  <virtualSignals name="iout4_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_res" hwSignal="res_sel" hwResource="//@hwResources.19" required="false"/>
  <virtualSignals name="user_defined_result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_res" hwSignal="res_sel" hwResource="//@hwResources.20" required="false"/>
  <virtualSignals name="Vout pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch1_io" hwSignal="pin" hwResource="//@hwResources.22"/>
  <virtualSignals name="Vin pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch2_io" hwSignal="pin" hwResource="//@hwResources.23"/>
  <virtualSignals name="Iout1 pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch3_io" hwSignal="pin" hwResource="//@hwResources.24"/>
  <virtualSignals name="Iout2 pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch4_io" hwSignal="pin" hwResource="//@hwResources.25"/>
  <virtualSignals name="Iout3 pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch5_io" hwSignal="pin" hwResource="//@hwResources.26"/>
  <virtualSignals name="Iout4 pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch6_io" hwSignal="pin" hwResource="//@hwResources.27"/>
  <virtualSignals name="User_Defined pin_signal" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch7_io" hwSignal="pin" hwResource="//@hwResources.28"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_a" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_b" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_c" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_d" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_e" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_f" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_queue_g" requiredAppName="ADC_QUEUE" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#0" requiredAppName="ADC_SCAN" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#1" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#2" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#3" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#4" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#5" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_appres_scan#6" requiredAppName="ADC_SCAN" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_hrpwm_1" requiredAppName="HRPWM">
    <downwardMapList xsi:type="ResourceModel:App" href="../../HRPWM/v4_1_22/HRPWM_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_hrpwm_2" requiredAppName="HRPWM" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_hrpwm_3" requiredAppName="HRPWM" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_hrpwm_4" requiredAppName="HRPWM" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_pwm_ccu8_1" requiredAppName="PWM_CCU8" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_pwm_ccu8_2" requiredAppName="PWM_CCU8" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_pwm_ccu8_3" requiredAppName="PWM_CCU8" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_pwm_ccu8_4" requiredAppName="PWM_CCU8" required="false"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_power_con_library" requiredAppName="CONTROL_LIB" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CONTROL_LIB/v4_0_12/CONTROL_LIB_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_cpu_4x" requiredAppName="CPU_CTRL_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CPU_CTRL_XMC4/v4_0_18/CPU_CTRL_XMC4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_cpu_1x" requiredAppName="CPU_CTRL_XMC1" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/appres_systimer" requiredAppName="SYSTIMER" required="false" requiringMode="SHARABLE"/>
  <hwResources name="Vout pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_a_pin" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port14/Port14_14.dd#//@provided.5"/>
  </hwResources>
  <hwResources name="Vin pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_b_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Iout1 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_c_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Iout2 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_d_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Iout3 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_e_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Iout4 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_f_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="User_Defined pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_chan_g_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Vout channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#0" resourceGroupUri="peripheral/vadc/0/group/*/ch/*" mResGrpUri="peripheral/vadc/0/group/*/ch/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.23"/>
  </hwResources>
  <hwResources name="Vin channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#1" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Iout1 channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#2" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Iout2 channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#3" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Iout3 channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#4" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Iout4 channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#5" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="User_Defined channel" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_adcchan#6" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Vout result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#0" resourceGroupUri="peripheral/vadc/0/group/*/result/*" mResGrpUri="peripheral/vadc/0/group/*/result/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.35"/>
  </hwResources>
  <hwResources name="Vin result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#1" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="Iout1 result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#2" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="Iout2 result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#3" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="Iout3 result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#4" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="Iout4 result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#5" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="User_Defined result" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_hwres_result#6" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="NVIC Node" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/hwres_nvicnode" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.9"/>
  </hwResources>
  <hwResources name="Vout pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_a_pin" resourceGroupUri="devicepackage/0/25" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.4"/>
  </hwResources>
  <hwResources name="Vin pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_b_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Iout1 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_c_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Iout2 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_d_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Iout3 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_e_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Iout4 pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_f_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="User_Defined pin" URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_hwres_chan_g_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1" systemDefined="true" sourceSignal="vout_pin" targetSignal="vout_channel" srcVirtualSignal="//@virtualSignals.0" targetVirtualSignal="//@virtualSignals.7"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2" systemDefined="true" sourceSignal="vin_pin" targetSignal="vin_channel" required="false" srcVirtualSignal="//@virtualSignals.1" targetVirtualSignal="//@virtualSignals.8"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3" systemDefined="true" sourceSignal="iout1_pin" targetSignal="iout1_channel" required="false" srcVirtualSignal="//@virtualSignals.2" targetVirtualSignal="//@virtualSignals.9"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4" systemDefined="true" sourceSignal="iout2_pin" targetSignal="iout2_channel" required="false" srcVirtualSignal="//@virtualSignals.3" targetVirtualSignal="//@virtualSignals.10"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5" systemDefined="true" sourceSignal="iout3_pin" targetSignal="iout3_channel" required="false" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.11"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6" systemDefined="true" sourceSignal="iout4_pin" targetSignal="iout4_channel" required="false" srcVirtualSignal="//@virtualSignals.5" targetVirtualSignal="//@virtualSignals.12"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7" systemDefined="true" sourceSignal="User_Defined_pin" targetSignal="user_defined_channel" required="false" srcVirtualSignal="//@virtualSignals.6" targetVirtualSignal="//@virtualSignals.13"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_res" systemDefined="true" sourceSignal="vout_result_select" targetSignal="vout_result" srcVirtualSignal="//@virtualSignals.30" targetVirtualSignal="//@virtualSignals.37"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_sel" systemDefined="true" sourceSignal="scan_select" targetSignal="vout_channel_select" targetVirtualSignal="//@virtualSignals.21" proxySrcVirtualSignalUri="http://resources/4.0.20/app/ADC_SCAN/0/vs_adc_scan_scan2channel" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.1"/>
    <srcVirtualSignal href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.1"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_sel" systemDefined="true" targetSignal="vout_channel_select" required="false" targetVirtualSignal="//@virtualSignals.21" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_iclass_sel" systemDefined="true" sourceSignal="iclass_select" targetSignal="vout_channel_iclass" targetVirtualSignal="//@virtualSignals.14" proxySrcVirtualSignalUri="http://resources/4.0.20/app/ADC_SCAN/0/vs_adc_scan_iclass2channel" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.2"/>
    <srcVirtualSignal href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_iclass_sel" systemDefined="true" targetSignal="vout_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.14" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#0" systemDefined="true" sourceSignal="event_period_match" targetSignal="trigger_input" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" proxyTargetVirtualSignalUri="http://resources/4.0.20/app/ADC_SCAN/0/vs_adc_scan_greqtr0sel" containingProxySignal="true">
    <targetVirtualSignal href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.4"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#0" systemDefined="true" sourceSignal="event_period_match" targetSignal="trigger_input" proxySrcVirtualSignalUri="http://resources/4.1.22/app/HRPWM/0/vs_ccu8_cc8_period_match_interrupt" proxyTargetVirtualSignalUri="http://resources/4.0.20/app/ADC_SCAN/0/vs_adc_scan_greqtr0sel" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.4"/>
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
    <targetVirtualSignal href="../../ADC_SCAN/v4_0_20/ADC_SCAN_0.app#//@virtualSignals.4"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#0" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#0" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_res" systemDefined="true" sourceSignal="vin_result_select" targetSignal="vin_result" required="false" srcVirtualSignal="//@virtualSignals.31" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#1/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_sel" systemDefined="true" targetSignal="vin_channel_select" required="false" targetVirtualSignal="//@virtualSignals.22" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#1/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_sel" systemDefined="true" targetSignal="vin_channel_select" required="false" targetVirtualSignal="//@virtualSignals.22" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#1/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_iclass_sel" systemDefined="true" targetSignal="vin_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.15" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#1/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_iclass_sel" systemDefined="true" targetSignal="vin_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.15" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#1" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#1" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#1" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#1" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_res" systemDefined="true" sourceSignal="iout1_result_select" targetSignal="iout1_result" required="false" srcVirtualSignal="//@virtualSignals.32" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#2/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_sel" systemDefined="true" targetSignal="iout1_channel_select" required="false" targetVirtualSignal="//@virtualSignals.23" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#2/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_sel" systemDefined="true" targetSignal="iout1_channel_select" required="false" targetVirtualSignal="//@virtualSignals.23" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#2/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_iclass_sel" systemDefined="true" targetSignal="iout1_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.16" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#2/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_iclass_sel" systemDefined="true" targetSignal="iout1_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.16" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#2" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#2" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#2" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#2" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_res" systemDefined="true" sourceSignal="iout2_result_select" targetSignal="iout2_result" required="false" srcVirtualSignal="//@virtualSignals.33" targetVirtualSignal="//@virtualSignals.40"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#3/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_sel" systemDefined="true" targetSignal="iout2_channel_select" required="false" targetVirtualSignal="//@virtualSignals.24" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#3/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_sel" systemDefined="true" targetSignal="iout2_channel_select" required="false" targetVirtualSignal="//@virtualSignals.24" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#3/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_iclass_sel" systemDefined="true" targetSignal="iout2_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.17" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#3/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_iclass_sel" systemDefined="true" targetSignal="iout2_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.17" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#3" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#3" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#3" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#3" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_res" systemDefined="true" sourceSignal="iout3_result_select" targetSignal="iout3_result" required="false" srcVirtualSignal="//@virtualSignals.34" targetVirtualSignal="//@virtualSignals.41"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#4/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_sel" systemDefined="true" targetSignal="iout3_channel_select" required="false" targetVirtualSignal="//@virtualSignals.25" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#4/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_sel" systemDefined="true" targetSignal="iout3_channel_select" required="false" targetVirtualSignal="//@virtualSignals.25" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#4/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_iclass_sel" systemDefined="true" targetSignal="iout3_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.18" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#4/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_iclass_sel" systemDefined="true" targetSignal="iout3_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.18" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#4" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#4" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#4" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#4" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_res" systemDefined="true" sourceSignal="iout4_result_select" targetSignal="iout4_result" required="false" srcVirtualSignal="//@virtualSignals.35" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#5/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_sel" systemDefined="true" targetSignal="iout4_channel_select" required="false" targetVirtualSignal="//@virtualSignals.26" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#5/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_sel" systemDefined="true" targetSignal="iout4_channel_select" required="false" targetVirtualSignal="//@virtualSignals.26" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#5/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_iclass_sel" systemDefined="true" targetSignal="iout4_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.19" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#5/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_iclass_sel" systemDefined="true" targetSignal="iout4_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.19" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#5" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#5" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#5" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#5" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_ressel/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_res" systemDefined="true" sourceSignal="user_defined_result_select" targetSignal="user_defined_result" required="false" srcVirtualSignal="//@virtualSignals.36" targetVirtualSignal="//@virtualSignals.43"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan#6/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_sel" systemDefined="true" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.27" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue#6/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_sel" systemDefined="true" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.27" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_scan_iclass#6/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_iclass_sel" systemDefined="true" targetSignal="user_defined_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.20" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_buck_vc_fix_fq_adc_queue_iclass#6/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_iclass_sel" systemDefined="true" targetSignal="user_defined_channel_iclass" required="false" targetVirtualSignal="//@virtualSignals.20" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#6" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_scan_trigger_in#6" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_pwm_ccu8_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#6" systemDefined="true" sourceSignal="event_period_match" required="false" proxySrcVirtualSignalUri="http://resources/4.1.32/app/PWM_CCU8/0/vs_ccu8_cc8_period_match_interrupt" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_hrpwm_pm_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/rarray_vs_adc_queue_trigger_in#6" systemDefined="true" sourceSignal="event_period_match" required="false" containingProxySignal="true">
    <srcVirtualSignal href="../../HRPWM/v4_1_22/HRPWM_0.app#//@virtualSignals.2"/>
  </connections>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_result_event_out/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_nvic_signal_in" systemDefined="true" sourceSignal="vout_result_event" targetSignal="nvic_node" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.29"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch1_io" systemDefined="true" sourceSignal="vout_pin" targetSignal="Vout pin_signal" srcVirtualSignal="//@virtualSignals.0" targetVirtualSignal="//@virtualSignals.44"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch1_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch1_io" systemDefined="true" sourceSignal="Vout pin_signal" targetSignal="vout_pin" srcVirtualSignal="//@virtualSignals.44" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch2_io" systemDefined="true" sourceSignal="vin_pin" targetSignal="Vin pin_signal" srcVirtualSignal="//@virtualSignals.1" targetVirtualSignal="//@virtualSignals.45"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch2_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch2_io" systemDefined="true" sourceSignal="Vin pin_signal" targetSignal="vin_pin" srcVirtualSignal="//@virtualSignals.45" targetVirtualSignal="//@virtualSignals.1"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch3_io" systemDefined="true" sourceSignal="iout1_pin" targetSignal="Iout1 pin_signal" srcVirtualSignal="//@virtualSignals.2" targetVirtualSignal="//@virtualSignals.46"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch3_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch3_io" systemDefined="true" sourceSignal="Iout1 pin_signal" targetSignal="iout1_pin" srcVirtualSignal="//@virtualSignals.46" targetVirtualSignal="//@virtualSignals.2"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch4_io" systemDefined="true" sourceSignal="iout2_pin" targetSignal="Iout2 pin_signal" srcVirtualSignal="//@virtualSignals.3" targetVirtualSignal="//@virtualSignals.47"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch4_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch4_io" systemDefined="true" sourceSignal="Iout2 pin_signal" targetSignal="iout2_pin" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.3"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch5_io" systemDefined="true" sourceSignal="iout3_pin" targetSignal="Iout3 pin_signal" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.48"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch5_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch5_io" systemDefined="true" sourceSignal="Iout3 pin_signal" targetSignal="iout3_pin" srcVirtualSignal="//@virtualSignals.48" targetVirtualSignal="//@virtualSignals.4"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch6_io" systemDefined="true" sourceSignal="iout4_pin" targetSignal="Iout4 pin_signal" srcVirtualSignal="//@virtualSignals.5" targetVirtualSignal="//@virtualSignals.49"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch6_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch6_io" systemDefined="true" sourceSignal="Iout4 pin_signal" targetSignal="iout4_pin" srcVirtualSignal="//@virtualSignals.49" targetVirtualSignal="//@virtualSignals.5"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch7_io" systemDefined="true" sourceSignal="User_Defined_pin" targetSignal="User_Defined pin_signal" srcVirtualSignal="//@virtualSignals.6" targetVirtualSignal="//@virtualSignals.50"/>
  <connections URI="http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/__pin_vs_buck_vc_fix_fq_adcch7_io/http://resources/4.1.4/app/BUCK_VC_FIX_FQ/0/vs_buck_vc_fix_fq_adcch7_io" systemDefined="true" sourceSignal="User_Defined pin_signal" targetSignal="User_Defined_pin" srcVirtualSignal="//@virtualSignals.50" targetVirtualSignal="//@virtualSignals.6"/>
</ResourceModel:App>
